# postgres
FROM postgres:10

# プロキシ設定
# ARG proxy_user="xxxxxx"
# ARG proxy_password="xxxxxx"
# ARG proxy_host="xxxx:8080"
# ARG no_proxy="xxxx,xxxx,xxxx"

# ENV HTTP_PROXY_USER ${proxy_user}
# ENV NO_PROXY ${no_proxy}
# ENV HTTP_PROXY_PASS ${proxy_password}
# ENV HTTP_PROXY http://${proxy_user}:${proxy_password}@${proxy_host}
# ENV HTTPS_PROXY http://${proxy_user}:${proxy_password}@${proxy_host}
# ENV http_proxy http://${proxy_user}:${proxy_password}@${proxy_host}
# ENV https_proxy http://${proxy_user}:${proxy_password}@${proxy_host}
# ENV proxy http://${proxy_user}:${proxy_password}@${proxy_host}

# RUN echo "Acquire::http::proxy \"http://${proxy_user}:${proxy_password}@${proxy_host}\";" >> /etc/apt/apt.conf \
#     && echo "Acquire::https::proxy \"http://${proxy_user}:${proxy_password}@${proxy_host}\";" >> /etc/apt/apt.conf